[[res_attrs]]
== Resource Properties

[[mandatory_attrs]]
=== Mandatory Properties

The following properties MUST be specified in a vCard representing a resource:

* FN
* UID
* KIND

[[res_kind]]
=== Special Notes:

==== KIND

Some of the possible values for the KIND property are "Location", "Individual",
"Device", or "Group".

Location is used for any physical location resource such as room, building, etc.

Individual is used for a human resource such as driver, technician, etc.

Device is used for a computing device such as an appliance, a computer, or a
network element.

Group is used to specify a group of resources with a specific skill set. For
example: drivers, electricians, etc.

[[existing_attrs]]
=== Base vCard Properties

The following properties defined in <<RFC6350>> or <<RFC2739>> make sense for
vCards representing resources (this list is not exhaustive, and other properties
might be applicable as well):

* ADR
* CATEGORIES
* EMAIL
* FBURL
* FN
* KIND
* MEMBER
* NOTE
* NICKNAME
* ORG
* PHOTO
* RELATED
* TZ
* UID

[[new_properties]]
=== New vCard Properties for resources

Format and cardinality of new vCard properties are defined as described in
<<RFC6350,section=3.3>>.

[[accessible]]
==== ACCESSIBLE

Purpose:: Specify if the resource is accessible to physically disabled people.

ValueType:: Boolean value.

Cardinality:: *1

ABNF::
+
[source%unnumbered]
----
ACCESSIBLE-param = "VALUE=boolean" / any-param
ACCESSIBLE-value = boolean
----

Default value:: FALSE.

Example value:: TRUE

[[access]]
==== ACCESSIBILITYINFO

Purpose:: Specify special resource accessibility info for the physically
disabled people.

ValueType:: URI value. It MAY also be a free-form text value.

Cardinality:: *

ABNF::
+
[source%unnumbered]
----
ACCESSIBILITYINFO-param = "VALUE=" ("text" / "uri") /
                           any-param
ACCESSIBILITYINFO-value = URI / text
----

Default value:: None

Example value:: http://www.example.com/room1_specialaccess.html

[[capacity]]
==== CAPACITY

Purpose:: Provide information on the capacity of the resource.

ValueType:: Integer.

Cardinality:: *1

ABNF::
+
[source%unnumbered]
----
CAPACITY-param = "VALUE=integer" / any-param
CAPACITY-value = integer
----

Default value:: None

Example value:: 10

[[inventorylist]]
==== INVENTORY

Purpose:: List other resources available as part of this resource.

ValueType:: Value MAY be a URI that could be a vCard. The vCard could be of the
KIND group whose members point to the various inventory items.
+
Value MAY also be a free form text listing one or more inventory items.

Cardinality:: *

ABNF::
+
[source%unnumbered]
----
INVENTORY-param = "VALUE=" ("text" / "uri") / any-param
INVENTORY-value = uri / text
----

Default value:: None

Example values:: Printer, Projector or http://www.example.com/Room1Inventory.vcf

[[locationtype]]
==== LOCATIONTYPE

Purpose:: Provide more information on the type of a LOCATION resource.

ValueType:: Text. The value SHOULD be one of the values defined in RFC 4589.

Cardinality:: *

ABNF::
+
[source%unnumbered]
----
LOCATIONTYPE-param = "VALUE=text" / any-param
LOCATIONTYPE-value = text
----

Default value:: None

Example value:: office

[[restrict]]
==== RESTRICTED

Purpose:: Specify if there are restrictions to physically accessing the
resource. For example locked doors, or other barriers.

ValueType:: Boolean value.

Cardinality:: *1

ABNF::
+
[source%unnumbered]
----
RESTRICTED-param = "VALUE=boolean" / any-param
RESTRICTED-value = boolean
----

Default value:: FALSE.
+
Absence of this property indicates no restriction to physically
accessing the resource.

Example value:: TRUE

[[restrictaccess_info]]
==== RESTRICTEDACCESSINFO

Purpose:: Specify extra information on physically accessing resources that have
restrictions. For example where to pick up keys to a locked resource.

ValueType:: URI value. It MAY also be a free-form text value.

Cardinality:: *

ABNF::
+
[source%unnumbered]
----
RESTRICTEDACCESSINFO-param = "VALUE=" ("text" / "uri") /
                             any-param
RESTRICTEDACCESSINFO-value = URI / text
----

Default value:: None

Example value:: http://www.example.com/room1_entryinfo.html

[[free]]
==== NOCOST

Purpose:: Specify if there is a cost associated with using the resource.

ValueType:: Boolean value.

Cardinality:: *1

ABNF::
+
[source%unnumbered]
----
NOCOST-param = "VALUE=boolean" / any-param
NOCOST-value = boolean
----

Special Notes:: If this property is absent, it indicates that the resource may
be booked free of cost.

Default value:: TRUE

Example value:: TRUE

[[cost_url]]
==== COSTINFO

Purpose:: Provide the URL pointing to complete pricing information for usage of
the resource.

ValueType:: URI value. It MAY also be a free-form text value.

Cardinality:: *

ABNF::
+
[source%unnumbered]
----
COSTINFO-param = "VALUE=" ("text" / "uri") / any-param
COSTINFO-value = uri / text
----

Default value:: None

Example value:: http://www.example.com/cost.html
